package org.gapito.jdwex.ui;

public enum ServerTreeNodeType {
	GENERIC, SERVER, DATABASE, SYSTABLES, SYSVIEWS, TABLES, VIEWS, SYNS, PROGRAMMABILITY, TABLE, VIEW, COLUMNS, KEYS, CONSTRAINTS, TRIGGERS, INDEXES, STATISTICS, SYSTABLE, SYSVIEW, COLUMN
}
